version: "3.8"

services:
  backend:
    build:
      context: ./  # O contexto agora é a raiz do diretório src
      dockerfile: ./backend/Dockerfile  # O Dockerfile está na pasta backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code/backend  # Volume para o backend
      - ./frontend:/code/frontend  # Volume para o frontend
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    networks:
      - app-network

volumes:
  mongodbdata:

networks:
  app-network:
    driver: bridge
